title = "1bit.pw"
base_url = "https://1bit.pw"
description = "Home of avitex"

compile_sass = true
highlight_code = true
build_search_index = true
generate_rss = true

taxonomies = [
	{name = "blog/tags", rss = true},
	{name = "blog/categories", rss = true}
]

[extra]
author = "avitex"

[[extra.main_menu]]
name = "blog"
url = "/blog"
sub = [
	{name = "latest", url = "/blog"},
	{name = "categories", url = "/blog/categories"},
	{name = "tags", url = "/blog/tags"}
]

[[extra.main_menu]]
name = "projects"
url = "/projects"
sub = [
	{name = "rust", url = "#rust"},
	{name = "elixir", url = "#elixir"},
	{name = "github", url = "https://github.com/avitex"}
]

[[extra.main_menu]]
name = "about"
url = "/about"
sub = [
	{name = "overview", url = "/about"},
	{name = "bio", url = "/about/bio"},
	{name = "social", url = "/about/social"}
]