status = { experimental = "red", development = "orange", hibernation = "inactive", maintained = "green" }

###############################################################################
# Rust

[project.rust-badgen]
lang = "rust"
crate = "badgen"
status = "hibernation"
github = "avitex/rust-badgen"
ci = true
published = true

[project.rust-dangerous]
lang = "rust"
crate = "dangerous"
status = "maintained"
github = "avitex/rust-dangerous"
ci = true
published = true

[project.rust-zc]
lang = "rust"
crate = "zc"
status = "maintained"
github = "avitex/rust-zc"
ci = true
published = true

[project.rust-aliasable]
lang = "rust"
crate = "aliasable"
status = "maintained"
github = "avitex/rust-aliasable"
ci = true
published = true

[project.rust-arae]
lang = "rust"
crate = "arae"
status = "experimental"
github = "avitex/rust-arae"
ci = false
published = true

[project.rust-dnscat]
lang = "rust"
crate = "dnscat"
status = "development"
github = "avitex/rust-dnscat"
ci = false
published = true

[project.rust-public-ip]
lang = "rust"
crate = "public-ip"
status = "maintained"
github = "avitex/rust-public-ip"
ci = true
published = true

[project.mdbook-tera]
lang = "rust"
crate = "mdbook-tera"
status = "maintained"
github = "avitex/mdbook-tera"
ci = true
published = true

[project.rust-abuseipdb]
lang = "rust"
crate = "abuseipdb"
status = "maintained"
github = "avitex/rust-abuseipdb"
ci = false
published = true

[project.rust-aliasable-deref-trait]
lang = "rust"
crate = "aliasable_deref_trait"
status = "maintained"
github = "avitex/rust-aliasable-deref-trait"
ci = false
published = true

[project.rust-feast]
lang = "rust"
crate = "feast"
status = "experimental"
github = "avitex/rust-feast"
ci = false
published = true

[project.battlelayer]
lang = "rust"
crate = "battlelayer"
status = "hibernation"
github = "avitex/battlelayer"
ci = false
published = false

###############################################################################
# Elixir

[project.elixir-glicko]
lang = "elixir"
hex = "glicko"
status = "maintained"
github = "avitex/elixir-glicko"
ci = false
published = true

[project.elixir-rcon]
lang = "elixir"
hex = "rcon"
status = "maintained"
github = "avitex/elixir-rcon"
ci = false
published = true

[project.elixir-vultr]
lang = "elixir"
hex = "vultr"
status = "hibernation"
github = "avitex/elixir-vultr"
ci = false
published = true

[project.elixir-gitlab]
lang = "elixir"
hex = "gitlab"
status = "hibernation"
github = "avitex/elixir-gitlab"
ci = false
published = false

[project.typed-struct-cast]
lang = "elixir"
hex = "typed-struct-cast"
status = "hibernation"
github = "avitex/typed-struct-cast"
ci = false
published = false
